### ISSUE TITLE
Missing branding div and logo

### ISSUE THREAD

**Issue by paulseto** [bigbluebutton/bbb-install#762]
The branding <div/> container is missing so a logo is not shown.

The server has been setup using `bbb-install.sh` on the 2.7 branch.

```
bbb-install.sh -w -v focal-270 -s baseline.allthejelly.com -d
```

The configuration file `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` contains
```
public:
  app:
    branding:
      displayBrandingArea: true
```
